name: mouse
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py39heb7d2ae_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.8=h166bdaf_0
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.3.0=pyh71513ae_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.0.9=py39h5a03fae_8
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.2=pyhd8ed1ab_0
  - cairo=1.16.0=ha61ee94_1012
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h74842e3_2
  - cryptography=39.0.0=py39hd598818_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dbus=1.13.6=h5008d03_3
  - expat=2.7.1=hecca717_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - flatbuffers=2.0.8=hcb278e6_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.1=py39heb7d2ae_0
  - freetype=2.14.1=ha770c72_0
  - frozenlist=1.7.0=py39h53edacf_0
  - gast=0.4.0=pyh9f0ad1d_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=hd590300_0
  - glib=2.84.0=h07242d1_0
  - glib-tools=2.84.0=h4833e2c_0
  - google-auth=2.40.3=pyhd8ed1ab_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.14=hecca717_2
  - grpc-cpp=1.47.1=h05bd8bd_7
  - grpcio=1.47.1=py39h712372c_7
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.41=h17648ed_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.9.0=nompi_py39h4dfffb9_100
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.14.0=nompi_h5231ba7_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jack=1.9.22=h11f4161_0
  - jpeg=9e=h0b41bf4_3
  - keras=2.10.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_1
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.20.1=hf9c8cef_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20220623.0=cxx17_h05df665_6
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=37_h0358290_openblas
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.87.0=h6312ad2_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h9b69904_4
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt=1.11.1=ha770c72_0
  - libgcrypt-devel=1.11.1=hb9d3cd8_0
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgcrypt-tools=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.84.0=h2ff4ddf_0
  - libgomp=15.2.0=h767d61c_7
  - libgpg-error=1.55=h3f2d84a_0
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=37_h47877c9_openblas
  - libllvm15=15.0.7=hadd5161_1
  - libltdl=2.4.3a=h5888daf_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopus=1.5.2=hd0c01bc_0
  - libpng=1.6.50=h421ea60_1
  - libpq=15.1=h2baec63_3
  - libprotobuf=3.21.12=hfc55251_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=252=h2a991cd_0
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.5.4=h5888daf_0
  - libudev1=253=h0b41bf4_0
  - libuuid=2.41.2=he9a06e4_0
  - libvorbis=1.3.7=h54a6638_2
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.9.4=hcb278e6_0
  - markdown=3.8.2=pyhd8ed1ab_0
  - markupsafe=3.0.2=py39h9399b63_1
  - matplotlib=3.9.1=py39hf3d152e_1
  - matplotlib-base=3.9.1=py39h0565ad7_2
  - mpg123=1.32.9=hc50e24c_0
  - multidict=6.6.3=py39h9399b63_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - ncurses=6.5=h2d0b736_3
  - nspr=4.37=h29cc59b_0
  - nss=3.117=h445c969_0
  - numpy=1.23.5=py39h3d75532_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=1.1.1w=hd590300_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py39h1b6b32d_0
  - pcre2=10.44=hc749103_2
  - pillow=9.4.0=py39h2320bf1_1
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - ply=3.11=pyhd8ed1ab_3
  - propcache=0.3.1=py39h9399b63_0
  - protobuf=4.21.12=py39h227be39_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulseaudio=16.1=h4ab2085_1
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.2.3=pyhe01879c_2
  - pyqt=5.15.7=py39h5c7b992_3
  - pyqt5-sip=12.11.0=py39h227be39_3
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.15=h47a2c10_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-flatbuffers=25.2.10=pyhbc23db3_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.6=h18908ee_6
  - re2=2022.06.01=h27087fc_1
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.7.12=py39h3d6467e_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.1.10=hdb0a2a9_1
  - tensorboard=2.10.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py39hd97740a_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.10.0=cpu_py39h4655687_0
  - tensorflow-base=2.10.0=cpu_py39h16601f7_0
  - tensorflow-estimator=2.10.0=cpu_py39heaff504_0
  - termcolor=3.1.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py39hd399759_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py39hd399759_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yarl=1.20.1=py39h9399b63_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - bmtk==0.0.8
      - imageio==2.37.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lazy-loader==0.4
      - mpmath==1.3.0
      - networkx==3.2.1
      - referencing==0.36.2
      - rpds-py==0.27.1
      - scikit-image==0.24.0
      - simmanager==0.8.3
      - sympy==1.14.0
      - tifffile==2024.8.30
prefix: /home/uni/miniforge3/envs/mouse
